/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TestServ_H
#define TestServ_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "test_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TestServIf {
 public:
  virtual ~TestServIf() {}
  virtual void ping(std::string& _return, const std::string& message) = 0;
};

class TestServIfFactory {
 public:
  typedef TestServIf Handler;

  virtual ~TestServIfFactory() {}

  virtual TestServIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TestServIf* /* handler */) = 0;
};

class TestServIfSingletonFactory : virtual public TestServIfFactory {
 public:
  TestServIfSingletonFactory(const boost::shared_ptr<TestServIf>& iface) : iface_(iface) {}
  virtual ~TestServIfSingletonFactory() {}

  virtual TestServIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TestServIf* /* handler */) {}

 protected:
  boost::shared_ptr<TestServIf> iface_;
};

class TestServNull : virtual public TestServIf {
 public:
  virtual ~TestServNull() {}
  void ping(std::string& /* _return */, const std::string& /* message */) {
    return;
  }
};

typedef struct _TestServ_ping_args__isset {
  _TestServ_ping_args__isset() : message(false) {}
  bool message :1;
} _TestServ_ping_args__isset;

class TestServ_ping_args {
 public:

  TestServ_ping_args(const TestServ_ping_args&);
  TestServ_ping_args& operator=(const TestServ_ping_args&);
  TestServ_ping_args() : message() {
  }

  virtual ~TestServ_ping_args() throw();
  std::string message;

  _TestServ_ping_args__isset __isset;

  void __set_message(const std::string& val);

  bool operator == (const TestServ_ping_args & rhs) const
  {
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const TestServ_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TestServ_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TestServ_ping_pargs {
 public:


  virtual ~TestServ_ping_pargs() throw();
  const std::string* message;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TestServ_ping_result__isset {
  _TestServ_ping_result__isset() : success(false) {}
  bool success :1;
} _TestServ_ping_result__isset;

class TestServ_ping_result {
 public:

  TestServ_ping_result(const TestServ_ping_result&);
  TestServ_ping_result& operator=(const TestServ_ping_result&);
  TestServ_ping_result() : success() {
  }

  virtual ~TestServ_ping_result() throw();
  std::string success;

  _TestServ_ping_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TestServ_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TestServ_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TestServ_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TestServ_ping_presult__isset {
  _TestServ_ping_presult__isset() : success(false) {}
  bool success :1;
} _TestServ_ping_presult__isset;

class TestServ_ping_presult {
 public:


  virtual ~TestServ_ping_presult() throw();
  std::string* success;

  _TestServ_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TestServClient : virtual public TestServIf {
 public:
  TestServClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TestServClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return, const std::string& message);
  void send_ping(const std::string& message);
  void recv_ping(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TestServProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<TestServIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TestServProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TestServProcessor(boost::shared_ptr<TestServIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &TestServProcessor::process_ping;
  }

  virtual ~TestServProcessor() {}
};

class TestServProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TestServProcessorFactory(const ::boost::shared_ptr< TestServIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< TestServIfFactory > handlerFactory_;
};

class TestServMultiface : virtual public TestServIf {
 public:
  TestServMultiface(std::vector<boost::shared_ptr<TestServIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TestServMultiface() {}
 protected:
  std::vector<boost::shared_ptr<TestServIf> > ifaces_;
  TestServMultiface() {}
  void add(boost::shared_ptr<TestServIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping(std::string& _return, const std::string& message) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping(_return, message);
    }
    ifaces_[i]->ping(_return, message);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TestServConcurrentClient : virtual public TestServIf {
 public:
  TestServConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TestServConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return, const std::string& message);
  int32_t send_ping(const std::string& message);
  void recv_ping(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
